"""add rendition job uniqueness

Revision ID: 1d1c2d5c5dcb
Revises: ef4e51e96594
Create Date: 2026-06-02 00:17:58.734332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1d1c2d5c5dcb"
down_revision: Union[str, Sequence[str], None] = "ef4e51e96594"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_jobs_rendition_id", "jobs", ["rendition_id"])
    op.create_unique_constraint(
        "uq_renditions_video_id_resolution", "renditions", ["video_id", "resolution"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_renditions_video_id_resolution", "renditions", type_="unique"
    )
    op.drop_constraint("uq_jobs_rendition_id", "jobs", type_="unique")
    # ### end Alembic commands ###
