"""initial schema

Revision ID: 3803c9b5f9f0
Revises:
Create Date: 2026-05-31 14:06:48.258994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3803c9b5f9f0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_bucket", sa.String(), nullable=True),
        sa.Column("source_filename", sa.String(), nullable=True),
        sa.Column("source_content_type", sa.String(), nullable=True),
        sa.Column("source_size_bytes", sa.Integer(), nullable=True),
        sa.Column("multipart_upload_id", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploading",
                "uploaded",
                "pending",
                "running",
                "done",
                "failed",
                name="processing_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "renditions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column("resolution", sa.String(), nullable=False),
        sa.Column("bitrate", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploading",
                "uploaded",
                "pending",
                "running",
                "done",
                "failed",
                name="processing_status",
            ),
            nullable=False,
        ),
        sa.Column("output_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column("rendition_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploading",
                "uploaded",
                "pending",
                "running",
                "done",
                "failed",
                name="processing_status",
            ),
            nullable=False,
        ),
        sa.Column("error", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rendition_id"], ["renditions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jobs")
    op.drop_table("renditions")
    op.drop_table("videos")
    # ### end Alembic commands ###
