"""add upload sessions and job state

Revision ID: 61da8987d8e1
Revises: 3803c9b5f9f0
Create Date: 2026-05-31 22:51:48.009011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "61da8987d8e1"
down_revision: Union[str, Sequence[str], None] = "3803c9b5f9f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("object_upload_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("part_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "completed", "aborted", "failed", name="upload_status"),
            nullable=False,
        ),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("aborted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_upload_sessions_status_created_at",
        "upload_sessions",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_upload_sessions_video_id", "upload_sessions", ["video_id"], unique=False
    )
    op.add_column("jobs", sa.Column("attempt_count", sa.Integer(), nullable=False))
    op.add_column("jobs", sa.Column("max_attempts", sa.Integer(), nullable=False))
    op.add_column(
        "jobs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "jobs", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "jobs", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index("ix_jobs_rendition_id", "jobs", ["rendition_id"], unique=False)
    op.create_index(
        "ix_jobs_status_created_at", "jobs", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_jobs_status_started_at", "jobs", ["status", "started_at"], unique=False
    )
    op.create_index("ix_jobs_video_id", "jobs", ["video_id"], unique=False)
    op.add_column("renditions", sa.Column("error", sa.String(), nullable=True))
    op.add_column(
        "renditions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "renditions",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "renditions",
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_renditions_status", "renditions", ["status"], unique=False)
    op.create_index("ix_renditions_video_id", "renditions", ["video_id"], unique=False)
    op.add_column(
        "videos",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_videos_status", "videos", ["status"], unique=False)
    op.drop_column("videos", "multipart_upload_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos",
        sa.Column(
            "multipart_upload_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_index("ix_videos_status", table_name="videos")
    op.drop_column("videos", "updated_at")
    op.drop_index("ix_renditions_video_id", table_name="renditions")
    op.drop_index("ix_renditions_status", table_name="renditions")
    op.drop_column("renditions", "completed_at")
    op.drop_column("renditions", "updated_at")
    op.drop_column("renditions", "created_at")
    op.drop_column("renditions", "error")
    op.drop_index("ix_jobs_video_id", table_name="jobs")
    op.drop_index("ix_jobs_status_started_at", table_name="jobs")
    op.drop_index("ix_jobs_status_created_at", table_name="jobs")
    op.drop_index("ix_jobs_rendition_id", table_name="jobs")
    op.drop_column("jobs", "finished_at")
    op.drop_column("jobs", "started_at")
    op.drop_column("jobs", "updated_at")
    op.drop_column("jobs", "created_at")
    op.drop_column("jobs", "max_attempts")
    op.drop_column("jobs", "attempt_count")
    op.drop_index("ix_upload_sessions_video_id", table_name="upload_sessions")
    op.drop_index("ix_upload_sessions_status_created_at", table_name="upload_sessions")
    op.drop_table("upload_sessions")
    # ### end Alembic commands ###
