"""add video playback path

Revision ID: f9f5fdbd3894
Revises: 3eeb3340d278
Create Date: 2026-06-04 02:14:21.863155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f9f5fdbd3894"
down_revision: Union[str, Sequence[str], None] = "3eeb3340d278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("videos", sa.Column("playback_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "playback_path")
    # ### end Alembic commands ###
